### ISSUE TITLE
#4_Создание пользователя

### ISSUE THREAD

**Issue by AlexanderMacakov** [AlexanderMacakov/LinksBox#2]
Я как пользователь хочу иметь логин, пароль, возможность добавить email, и менять их

**Comment by AlexanderMacakov** [comment]
Так же указать Имя и Фамилию

**Comment by AlexanderMacakov** [comment]
Думаю для пользователя `class Person`
нужно добавить поля :
```
login
firstName
lastName
email
password
ArrayList<Link> linksPerson;
```

**Comment by hamster4n** [comment]
login -> id

**Comment by hamster4n** [comment]
id
firstName
lastName
email
password
TreeSet<Link> links;
TreeSet<Catalog> catalogs;
